name: Publish to NPM

permissions:
  contents: write
  id-token: write  # Required for OIDC

# Manually triggered workflow
on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        package-dir: [js]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: ./${{ matrix.package-dir }}
        run: npm install

      - name: Lint
        working-directory: ./${{ matrix.package-dir }}
        run: npm run lint

      - name: Configure Git
        run: |
          git config --global user.email "hi@reclaimprotocol.org"
          git config --global user.name "Reclaim CI"

      - name: Publish to NPM
        working-directory: ./${{ matrix.package-dir }}
        run: npm run publish:pkg
